# Generated by Django 3.1.3 on 2023-03-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company_detail',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
