# Generated by Django 3.1.3 on 2023-05-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student',
        ),
    ]
