# Generated by Django 3.1.3 on 2023-06-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_profile_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
