# Generated by Django 3.1.3 on 2023-06-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
